name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: pi/wrapper/go.mod

      - name: Run tests
        working-directory: pi/wrapper
        run: go test -v ./...
